### ISSUE TITLE
Question about chat format

### ISSUE THREAD

**Issue by LeAnhTuan0810** [FlickerProjects/TrChat#18]
**How to create chat format for each group (Luckperms)** 'English'

**Comment by 157946a** [comment]
Yours is very simple, just create a new content below-requirement: null,-requirement: null is at the same level as the first one, and then just change the configuration normally, write null as a comparison format, check papi *%luckperms_in_group_vip% == *yes is Kether grammar writing; js: "%luckperms_in_group_vip%" == "yes" is js writing, and if you have any questions, you can ask questions here instead of GitHub: https://discord.com/channels/760802420552105995 /884258283664310273

**Comment by LeAnhTuan0810** [comment]
https://discord.com/channels/760802420552105995
I can not come in (Dean Le#2431)

**Comment by 157946a** [comment]
You are chinese?

**Comment by LeAnhTuan0810** [comment]
> You are chinese?

No

**Comment by 157946a** [comment]
Try to use VPN to enter the link

**Comment by LeAnhTuan0810** [comment]
> Try to use VPN to enter the link

hm i can't access channels it says me you don't have permission
Can you send me an example chat format for each rank?  default->vip->mvp

**Comment by 157946a** [comment]
The different chat formats of different groups are very simple. Look carefully at the format I wrote to you. https://paste.helpch.at/nebexuqusi.pl
Discord does not need any permissions to enter, unless you don't have a registered account, etc.

**Comment by LeAnhTuan0810** [comment]
> The different chat formats of different groups are very simple. Look carefully at the format I wrote to you. https://paste.helpch.at/nebexuqusi.pl
> Discord does not need any permissions to enter, unless you don't have a registered account, etc.

Thanks

**Comment by LeAnhTuan0810** [comment]
https://sourceb.in/uKO5mofuZM
Can you update the color hex? I can't use color hex here

**Comment by 157946a** [comment]
I just talked to the maintainer about the RGB format and waited for him to push the new version.
